name: Vit-SSL
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pytorch::pytorch=2.0.1
  - pytorch::pytorch-cuda=11.8
  - pytorch::torchvision=0.15.2
  - pytorch::torchaudio=2.0.2
  - omegaconf
  - torchmetrics=0.10.3
  - fvcore
  - iopath
  - pip
  - pip:
    - git+https://github.com/facebookincubator/submitit
    - nibabel
    - loguru
