MODEL:
  WEIGHTS: ''
compute_precision:
  grad_scaler: true
  teacher:
    backbone:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
  student:
    backbone:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp32
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp32
        buffer_dtype: fp32
dino:
  loss_weight: 1.0
  head_n_prototypes: 32768  # MRI画像用に削減
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
  koleo_loss_weight: 0.1
ibot:
  loss_weight: 1.0
  mask_sample_probability: 0.3  # MRI画像用に調整
  mask_ratio_min_max:
  - 0.15  # より保守的なマスク比率
  - 0.45
  separate_head: false
  head_n_prototypes: 32768  # MRI画像用に削減
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
train:
  batch_size_per_gpu: 4  # 大きな画像サイズのため削減
  dataset_path: "MriDataset:path=/path/to/mri/data"  # MRIデータセットのパス
  output_dir: ./output_mri
  saveckp_freq: 10  # より頻繁なチェックポイント保存
  seed: 42
  num_workers: 4  # I/O負荷を考慮して削減
  OFFICIAL_EPOCH_LENGTH: 500  # MRIデータ量に応じて調整
  cache_dataset: false  # 大きなデータのためキャッシュを無効化
  centering: "centering"
student:
  arch: vit_large  # またはvit_base
  patch_size: 16
  drop_path_rate: 0.1  # 医用画像用に調整
  layerscale: 1.0e-05
  drop_path_uniform: true
  pretrained_weights: ''
  ffn_layer: "mlp"
  block_chunks: 0
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  num_register_tokens: 0
  interpolate_antialias: false
  interpolate_offset: 0.1
  # MRI画像用のパラメータ
  in_chans: 3  # RGB変換後のチャネル数
teacher:
  momentum_teacher: 0.996  # より安定した学習のため増加
  final_momentum_teacher: 1
  warmup_teacher_temp: 0.04
  teacher_temp: 0.04  # MRI画像用に調整
  warmup_teacher_temp_epochs: 20  # より長いウォームアップ
optim:
  epochs: 200  # より長い学習
  weight_decay: 0.04
  weight_decay_end: 0.4
  base_lr: 0.0005  # MRI画像用に調整
  lr: 0.  # will be set after applying scaling rule
  warmup_epochs: 20  # より長いウォームアップ
  min_lr: 1.0e-06
  clip_grad: 3.0
  freeze_last_layer_epochs: 2
  scaling_rule: sqrt_wrt_1024
  patch_embed_lr_mult: 0.1  # パッチ埋め込み層の学習率を抑制
  layerwise_decay: 0.8  # より強い層別減衰
  adamw_beta1: 0.9
  adamw_beta2: 0.95  # より安定した学習
crops:
  global_crops_scale:
  - 0.6  # 脳の重要な構造を保持
  - 1.0
  local_crops_number: 6  # 計算負荷を考慮して削減
  local_crops_scale:
  - 0.15  # より大きな局所領域
  - 0.6
  global_crops_size: 1024  # MRI画像のサイズ
  local_crops_size: 256   # 局所クロップのサイズ
evaluation:
  eval_period_iterations: 2500  # より頻繁な評価 