MODEL:
  WEIGHTS: ''
# 分散学習を無効化 - 単一GPU用設定
compute_precision:
  grad_scaler: true
  teacher:
    backbone:
      sharding_strategy: NO_SHARD  # 分散学習無効化: SHARD_GRAD_OP → NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: NO_SHARD  # 分散学習無効化: SHARD_GRAD_OP → NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: NO_SHARD  # 分散学習無効化: SHARD_GRAD_OP → NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
  student:
    backbone:
      sharding_strategy: NO_SHARD  # 分散学習無効化: SHARD_GRAD_OP → NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: NO_SHARD  # 分散学習無効化: SHARD_GRAD_OP → NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp32
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: NO_SHARD  # 分散学習無効化: SHARD_GRAD_OP → NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp32
        buffer_dtype: fp32
dino:
  loss_weight: 1.0
  head_n_prototypes: 16384  # VitS用に削減: 65536 → 16384
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
  koleo_loss_weight: 0.1
ibot:
  loss_weight: 1.0
  mask_sample_probability: 0.3  # MRI画像用に調整: 0.5 → 0.3
  mask_ratio_min_max:
  - 0.15  # より保守的なマスク比率: 0.1 → 0.15
  - 0.45  # より保守的なマスク比率: 0.5 → 0.45
  separate_head: false
  head_n_prototypes: 16384  # VitS用に削減: 65536 → 16384
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
train:
  batch_size_per_gpu: 8  # VitS用に適切なサイズ: 64 → 8
  dataset_path: "MriDataset:path=/path/to/mri/data"  # MRIデータセットを指定
  output_dir: ./output_mri_vits
  saveckp_freq: 10  # より頻繁なチェックポイント保存: 20 → 10
  seed: 42
  num_workers: 4  # 適切なワーカー数: 10 → 4
  OFFICIAL_EPOCH_LENGTH: 500  # MRIデータ量に応じて調整: 1250 → 500
  cache_dataset: false  # 大きなデータのためキャッシュを無効化: true → false
  centering: "centering"
student:
  arch: vit_small  # VitS使用: vit_large → vit_small
  patch_size: 14  # VitS標準設定: 16 → 14
  drop_path_rate: 0.1  # VitS用に調整: 0.3 → 0.1
  layerscale: 1.0e-05
  drop_path_uniform: true
  pretrained_weights: ''
  ffn_layer: "mlp"
  block_chunks: 0
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  num_register_tokens: 0
  interpolate_antialias: false
  interpolate_offset: 0.1
  in_chans: 3  # RGB変換後のチャネル数
teacher:
  momentum_teacher: 0.996  # より安定した学習: 0.992 → 0.996
  final_momentum_teacher: 1
  warmup_teacher_temp: 0.04
  teacher_temp: 0.04  # MRI画像用に調整: 0.07 → 0.04
  warmup_teacher_temp_epochs: 20  # より長いウォームアップ: 30 → 20
optim:
  epochs: 200  # より長い学習: 100 → 200
  weight_decay: 0.04
  weight_decay_end: 0.4
  base_lr: 0.0005  # MRI画像用に調整: 0.004 → 0.0005
  lr: 0.  # will be set after applying scaling rule
  warmup_epochs: 10
  min_lr: 1.0e-06
  clip_grad: 3.0
  freeze_last_layer_epochs: 1
  scaling_rule: sqrt_wrt_1024
  patch_embed_lr_mult: 0.1  # パッチ埋め込み層の学習率を抑制: 0.2 → 0.1
  layerwise_decay: 0.8  # より強い層別減衰: 0.9 → 0.8
  adamw_beta1: 0.9
  adamw_beta2: 0.95  # より安定した学習: 0.999 → 0.95
crops:
  global_crops_scale:
  - 0.6  # 脳の重要な構造を保持: 0.32 → 0.6
  - 1.0
  local_crops_number: 6  # 計算負荷を考慮して削減: 8 → 6
  local_crops_scale:
  - 0.15  # より大きな局所領域: 0.05 → 0.15
  - 0.6   # より大きな局所領域: 0.32 → 0.6
  global_crops_size: 896  # load_data.pyのTARGET_SIZEに合わせて調整: 224 → 896
  local_crops_size: 224   # 局所クロップのサイズ: 96 → 224
evaluation:
  eval_period_iterations: 1000  # より頻繁な評価: 12500 → 1000 